# Generated by Django 5.2.1 on 2025-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_supplier_purchaseitem_purchase_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='total_price',
            new_name='ht',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_tva_price',
            new_name='ttc',
        ),
        migrations.AddField(
            model_name='purchase',
            name='soumis_tva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
