# Generated by Django 5.2.1 on 2025-05-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_total_price_purchaseitem_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
