# Generated by Django 5.2.1 on 2025-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_purchase_total_amount_purchase_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='code',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
