# Generated by Django 5.2.1 on 2025-05-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_model_battery_charging_model_battery_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='body_water_resistant',
            new_name='bodyother',
        ),
        migrations.RemoveField(
            model_name='model',
            name='sound_loudspeaker',
        ),
    ]
